Рейтинг с сортировкой по винрейту
Salaron/mafia pull request #1
Opened 2023-10-17 16:19 UTC by VadimKarelov

2023-10-31 18:10 UTC, Salaron requested changes

2023-10-31 18:10 UTC, Salaron commented on MafiaLib/Statistic/StatsProvider.cs
> +        // ������������ ����, � ������� ������ 5 �����
кракозябры (чекни кодировку файла)

2023-10-31 18:10 UTC, Salaron commented on MafiaLib/Statistic/StatsProvider.cs
> +            .Where(user => user.WinGames.Count() > 5);
добавь `.ToListAsync()`, чтобы каждый раз запрос к бд не делать.

2023-10-31 18:10 UTC, Salaron commented on MafiaLib/Statistic/StatsProvider.cs
> +            userTop.Add(new(winrate, user));
new убрать можно

2023-10-31 18:10 UTC, Salaron commented on MafiaStatsBot/Commands/TotalStatsCommandHandler.cs
> +        var topTemplate = string.Join('\n', stats.UserTop.Select(x => $"{++i}\t{Math.Round(x.Winrate * 100, 2)}%\t[{x.User.Name}]()tg://user?id={x.User.Id}"));
поправь markdown `[{x.User.Name}](tg://user?id={x.User.UserId})`

User.id - айдишник в БД
User.UserId - айдишник в ТГ (да, легко ошибиться)

2023-10-31 18:10 UTC, Salaron commented on MafiaStatsBot/Commands/TotalStatsCommandHandler.cs
>          await botClient.SendTextMessageAsync(message.Chat.Id, template, cancellationToken: token);
и чтобы упоминание через markdown работало, добавь тут: `disableNotification: false, parseMode: ParseMode.MarkdownV2,` (перед cancelattionToken)

2023-10-31 18:10 UTC, Salaron commented on MafiaLib/Statistic/StatsProvider.cs
> +            var playCount = await appDbContext.GameResults
если не сложно, вытащи этот запрос в приватное поле и перееюзай тут и в методе ниже

2023-10-31 18:10 UTC, Salaron commented on MafiaLib/Statistic/StatsByChat.cs
> +    public List<(double Winrate, TgUser User)> UserTop { get; set; }
в кортежах переменные в camel case именуются (название с мелкой буквы)

2023-10-31 18:10 UTC, Salaron commented on MafiaStatsBot/Commands/TotalStatsCommandHandler.cs
> +        var topTemplate = string.Join('\n', stats.UserTop.Select(x => $"{++i}\t{Math.Round(x.Winrate * 100, 2)}%\t[{x.User.Name}]()tg://user?id={x.User.Id}"));
и лучше кажется пожертвовать строки кода, но написать читабельно, а то тяжко

сделай заполнение темплейта через цикл. лучше заюзать ещё и stringbuilder

2023-11-03 19:47 UTC, VadimKarelov commented on MafiaLib/Statistic/StatsProvider.cs
> +            var playCount = await appDbContext.GameResults
Не стал вытаскивать, т.к. переделал полностью рейтинг

2024-01-13 05:12 UTC, Salaron approved these changes

2024-01-13 05:12 UTC, merged